# see also: ./Dockerfile.jvm

FROM registry.access.redhat.com/ubi8/openjdk-11:1.11

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

USER root
COPY cacerts/ /etc/pki/ca-trust/source/anchors/
# Update ${JAVA_HOME}/lib/security/cacerts (https://access.redhat.com/solutions/3076491)
RUN update-ca-trust


# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=jboss target/quarkus-app/lib/ /deployments/lib/
COPY --chown=jboss target/quarkus-app/*.jar /deployments/
COPY --chown=jboss target/quarkus-app/app/ /deployments/app/
COPY --chown=jboss target/quarkus-app/quarkus/ /deployments/quarkus/


USER jboss
ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

EXPOSE 8080
